name: Docker Image Publish

on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Model and Build
        run: |
          mkdir -p Jetelina/app/resources/config
          curl -fsSL "https://github.com{{ github.repository }}/releases/download/v4.0.0/model_quantized.onnx" -o Jetelina/app/resources/config/model_quantized.onnx

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/jetelina:latest
